In [1]:
from sklearn.decomposition import TruncatedSVD
from sklearn.cluster import KMeans

import numpy as np
import pandas as pd

In [32]:
embed = np.load("./content_embedding.npy")

In [33]:
embed.shape

(13524, 128)

In [34]:
embed[:, 0]

array([ 0.00348971,  0.01093413,  0.01815927, ..., -0.02049293,
       -0.06177155,  0.09914625], dtype=float32)

In [35]:
embed[1:, 0]

array([ 0.01093413,  0.01815927,  0.02203978, ..., -0.02049293,
       -0.06177155,  0.09914625], dtype=float32)

In [36]:
embed = embed[1:]

In [37]:
svd = TruncatedSVD(n_components=20)
content_vecs = svd.fit_transform(embed)

In [38]:
content_vecs.shape

(13523, 20)

In [39]:
content_vecs

array([[ 0.29857266,  0.0828594 ,  0.10337925, ..., -0.05289454,
        -0.04786237,  0.01002183],
       [ 0.29416677,  0.11227994, -0.04767716, ...,  0.05001845,
        -0.05255706,  0.02543679],
       [-0.22071125,  0.04720166,  0.08526865, ...,  0.00883699,
         0.01770988,  0.03280997],
       ...,
       [-0.00494652, -0.05653199, -0.04470852, ..., -0.02753389,
         0.03068023,  0.01990469],
       [ 0.25516766, -0.11038473,  0.04874474, ..., -0.04982777,
         0.06112582, -0.05504936],
       [ 0.43774703,  0.11116546, -0.13141455, ..., -0.09800366,
        -0.04020726,  0.04884924]], dtype=float32)

In [41]:
content_vecs = pd.DataFrame(content_vecs)

In [42]:
content_vecs.head(2)

0         1         2         3         4         5         6   \
0  0.298573  0.082859  0.103379  0.019431 -0.108116  0.069238 -0.122686   
1  0.294167  0.112280 -0.047677  0.030680 -0.053393 -0.071304 -0.158679   

         7         8         9         10        11        12        13  \
0  0.034020  0.106384  0.013467  0.049322  0.044373 -0.019987 -0.051152   
1 -0.008623  0.041525  0.016410 -0.005720 -0.040753 -0.010178  0.045152   

         14        15        16        17        18        19  
0  0.002223 -0.027400 -0.045768 -0.052895 -0.047862  0.010022  
1  0.017016  0.018646 -0.058797  0.050018 -0.052557  0.025437

In [43]:
content_vecs.reset_index(inplace=True)

In [44]:
content_vecs.columns = ["content_id"] + ["nn_svd"+str(i) for i in range(20)]

In [45]:
content_vecs.head(2)

content_id   nn_svd0   nn_svd1   nn_svd2   nn_svd3   nn_svd4   nn_svd5  \
0           0  0.298573  0.082859  0.103379  0.019431 -0.108116  0.069238   
1           1  0.294167  0.112280 -0.047677  0.030680 -0.053393 -0.071304   

    nn_svd6   nn_svd7   nn_svd8  ...  nn_svd10  nn_svd11  nn_svd12  nn_svd13  \
0 -0.122686  0.034020  0.106384  ...  0.049322  0.044373 -0.019987 -0.051152   
1 -0.158679 -0.008623  0.041525  ... -0.005720 -0.040753 -0.010178  0.045152   

   nn_svd14  nn_svd15  nn_svd16  nn_svd17  nn_svd18  nn_svd19  
0  0.002223 -0.027400 -0.045768 -0.052895 -0.047862  0.010022  
1  0.017016  0.018646 -0.058797  0.050018 -0.052557  0.025437  

[2 rows x 21 columns]

In [46]:
kmeans = KMeans(n_clusters=35)
content_clusters = kmeans.fit_predict(content_vecs)

In [47]:
content_clusters.shape

(13523,)

In [48]:
content_vecs["nn_cluster"] = content_clusters

In [49]:
content_vecs.to_csv("./content_nn.csv", index=False)